# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e69851aa54990bf7e30d9b26feba6fdbb2de438e2278d0c95a1736af4f3b3daf1e93e113b19acaa23dd29c8be100a5b68d2631aff9afde505bddf340211f96e6

test:
  secret_key_base: 2ec8067ad12986477ae522e07de050abcea4dff320fb9aac674071675d0e0ae794967cedef31ce2aa5b1334c59da26fb1948e95f53049ecb9a38a56073aa4e57

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
